<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Luke Freudenheim">
<meta name="description" content="In this report, we will compare different types of statistical models. We will start by answering some conceptual questions about models, cross-validation, and prediction. Next we will look at a heart disease data set and explore the data set. After this, we will fit many types of models onto this data set while using cross-validation. Lastly, we will compare the different types of models in terms of accuracy by using a confusion matrix.">

<title>ST 558 Homework 5</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ST 558 Homework 5</h1>
</div>

<div>
  <div class="description">
    In this report, we will compare different types of statistical models. We will start by answering some conceptual questions about models, cross-validation, and prediction. Next we will look at a heart disease data set and explore the data set. After this, we will fit many types of models onto this data set while using cross-validation. Lastly, we will compare the different types of models in terms of accuracy by using a confusion matrix.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Luke Freudenheim </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="task-1-conceptual-questions" class="level1">
<h1>Task 1: Conceptual Questions</h1>
<ol type="1">
<li>What is the purpose of using cross-validation when fitting a random forest model?</li>
</ol>
<blockquote class="blockquote">
<p>The purpose of using cross-validation for a random forest model is to look into tuning of the folds. You can use it to figure out the best value of the folds to be at which provides the most accurate model.</p>
</blockquote>
<ol start="2" type="1">
<li>Describe the bagged tree algorithm.</li>
</ol>
<blockquote class="blockquote">
<p>A bagged tree algorithm takes multiple random samples (or bootstraps) of the original data set. It would then train a model on that sample from the original data set. The final prediction values are the average of all of these predictions from the bootstraps.</p>
</blockquote>
<ol start="3" type="1">
<li>What is meant by a general linear model?</li>
</ol>
<blockquote class="blockquote">
<p>A general linear model is a broader type of linear model that has a continuous response variable and allows for both continuous and categorical predictors.</p>
</blockquote>
<ol start="4" type="1">
<li>When fitting a multiple linear regression model, what does adding an interaction term do? That is, what does it allow the model to do differently as compared to when it is not included in the model?</li>
</ol>
<blockquote class="blockquote">
<p>Adding an interaction term into a model allows you to examine how a certain predictor behaves under different values of another variable.</p>
</blockquote>
<ol start="5" type="1">
<li>Why do we split our data into a training and test set?</li>
</ol>
<blockquote class="blockquote">
<p>We split the data into a training and test set so that we can test our models in terms of accuracy. We are able to train our models using the training set and then test their predictions they make on the test set.</p>
</blockquote>
</section>
<section id="task-2-fitting-models" class="level1">
<h1>Task 2: Fitting Models</h1>
<section id="reading-in-the-data" class="level2">
<h2 class="anchored" data-anchor-id="reading-in-the-data">Reading in the Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>heart_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"heart.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 918 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): Sex, ChestPainType, RestingECG, ExerciseAngina, ST_Slope
dbl (7): Age, RestingBP, Cholesterol, FastingBS, MaxHR, Oldpeak, HeartDisease

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(heart_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 12
    Age Sex   ChestPainType RestingBP Cholesterol FastingBS RestingECG MaxHR
  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;             &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
1    40 M     ATA                 140         289         0 Normal       172
2    49 F     NAP                 160         180         0 Normal       156
3    37 M     ATA                 130         283         0 ST            98
4    48 F     ASY                 138         214         0 Normal       108
5    54 M     NAP                 150         195         0 Normal       122
6    39 M     NAP                 120         339         0 Normal       170
# ℹ 4 more variables: ExerciseAngina &lt;chr&gt;, Oldpeak &lt;dbl&gt;, ST_Slope &lt;chr&gt;,
#   HeartDisease &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="exploring-the-data-set" class="level2">
<h2 class="anchored" data-anchor-id="exploring-the-data-set">Exploring the Data Set</h2>
<p>We will now explore some summaries of our data set. We will look at missingness in values along with relationships of variables to HeartDisease (our response).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking on Missingness in Data Set</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(heart_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking out summary of data and relationships</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(heart_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Age            Sex            ChestPainType        RestingBP    
 Min.   :28.00   Length:918         Length:918         Min.   :  0.0  
 1st Qu.:47.00   Class :character   Class :character   1st Qu.:120.0  
 Median :54.00   Mode  :character   Mode  :character   Median :130.0  
 Mean   :53.51                                         Mean   :132.4  
 3rd Qu.:60.00                                         3rd Qu.:140.0  
 Max.   :77.00                                         Max.   :200.0  
  Cholesterol      FastingBS       RestingECG            MaxHR      
 Min.   :  0.0   Min.   :0.0000   Length:918         Min.   : 60.0  
 1st Qu.:173.2   1st Qu.:0.0000   Class :character   1st Qu.:120.0  
 Median :223.0   Median :0.0000   Mode  :character   Median :138.0  
 Mean   :198.8   Mean   :0.2331                      Mean   :136.8  
 3rd Qu.:267.0   3rd Qu.:0.0000                      3rd Qu.:156.0  
 Max.   :603.0   Max.   :1.0000                      Max.   :202.0  
 ExerciseAngina        Oldpeak          ST_Slope          HeartDisease   
 Length:918         Min.   :-2.6000   Length:918         Min.   :0.0000  
 Class :character   1st Qu.: 0.0000   Class :character   1st Qu.:0.0000  
 Mode  :character   Median : 0.6000   Mode  :character   Median :1.0000  
                    Mean   : 0.8874                      Mean   :0.5534  
                    3rd Qu.: 1.5000                      3rd Qu.:1.0000  
                    Max.   : 6.2000                      Max.   :1.0000  </code></pre>
</div>
</div>
<p>We will now look at some relationships between variables to our response variable. First, we will look at a contingency table of sex vs.&nbsp;heart disease.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(heart_data<span class="sc">$</span>Sex, heart_data<span class="sc">$</span>HeartDisease)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      0   1
  F 143  50
  M 267 458</code></pre>
</div>
</div>
<p>We will now look at a couple of correlations. We will look at the correlation between resting BP and heart disease, and cholesterol level and heart disease.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation between resting BP and Heart Disease</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(heart_data<span class="sc">$</span>RestingBP, heart_data<span class="sc">$</span>HeartDisease)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.107589</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation between cholesterol and Heart Disease</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(heart_data<span class="sc">$</span>Cholesterol, heart_data<span class="sc">$</span>HeartDisease)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.2327406</code></pre>
</div>
</div>
<p>Next, we will create a factor version of the HeartDisease variable and remove unnecessary variables in our data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>heart_data <span class="ot">&lt;-</span> heart_data <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">HeartDiseaseFactor =</span> <span class="fu">as.factor</span>(HeartDisease)) <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(HeartDisease, ST_Slope))</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>heart_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 918 × 11
     Age Sex   ChestPainType RestingBP Cholesterol FastingBS RestingECG MaxHR
   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;             &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
 1    40 M     ATA                 140         289         0 Normal       172
 2    49 F     NAP                 160         180         0 Normal       156
 3    37 M     ATA                 130         283         0 ST            98
 4    48 F     ASY                 138         214         0 Normal       108
 5    54 M     NAP                 150         195         0 Normal       122
 6    39 M     NAP                 120         339         0 Normal       170
 7    45 F     ATA                 130         237         0 Normal       170
 8    54 M     ATA                 110         208         0 Normal       142
 9    37 M     ASY                 140         207         0 Normal       130
10    48 F     ATA                 120         284         0 Normal       120
# ℹ 908 more rows
# ℹ 3 more variables: ExerciseAngina &lt;chr&gt;, Oldpeak &lt;dbl&gt;,
#   HeartDiseaseFactor &lt;fct&gt;</code></pre>
</div>
</div>
<p>We will now create dummy variables from the categorical predictors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a set of dummy variables</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>dummies <span class="ot">&lt;-</span> <span class="fu">dummyVars</span>( <span class="sc">~</span> Sex <span class="sc">+</span> ExerciseAngina <span class="sc">+</span> ChestPainType <span class="sc">+</span> RestingECG, <span class="at">data =</span> heart_data)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the syntax given in the caret file to show dummy variables</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">predict</span>(dummies, <span class="at">newdata =</span> heart_data))</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Binding the data frames into the new data</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>heart_data_new <span class="ot">&lt;-</span> <span class="fu">cbind</span>(heart_data, df)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(heart_data_new)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Age Sex ChestPainType RestingBP Cholesterol FastingBS RestingECG MaxHR
1  40   M           ATA       140         289         0     Normal   172
2  49   F           NAP       160         180         0     Normal   156
3  37   M           ATA       130         283         0         ST    98
4  48   F           ASY       138         214         0     Normal   108
5  54   M           NAP       150         195         0     Normal   122
6  39   M           NAP       120         339         0     Normal   170
  ExerciseAngina Oldpeak HeartDiseaseFactor SexF SexM ExerciseAnginaN
1              N     0.0                  0    0    1               1
2              N     1.0                  1    1    0               1
3              N     0.0                  0    0    1               1
4              Y     1.5                  1    1    0               0
5              N     0.0                  0    0    1               1
6              N     0.0                  0    0    1               1
  ExerciseAnginaY ChestPainTypeASY ChestPainTypeATA ChestPainTypeNAP
1               0                0                1                0
2               0                0                0                1
3               0                0                1                0
4               1                1                0                0
5               0                0                0                1
6               0                0                0                1
  ChestPainTypeTA RestingECGLVH RestingECGNormal RestingECGST
1               0             0                1            0
2               0             0                1            0
3               0             0                0            1
4               0             0                1            0
5               0             0                1            0
6               0             0                1            0</code></pre>
</div>
</div>
</section>
</section>
<section id="split-the-data" class="level1">
<h1>Split the Data</h1>
<p>Now, we will split our data set into a training set and a testing set of data. We will put 80% of the data in the training set and then 20% of the data into the testing set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">72</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co">#indices to split on</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(heart_data_new), <span class="at">size =</span> <span class="fu">nrow</span>(heart_data_new)<span class="sc">*</span><span class="fl">0.8</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(heart_data_new), train)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co">#subset</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>HeartTrain <span class="ot">&lt;-</span> heart_data_new[train, ]</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>HeartTest <span class="ot">&lt;-</span> heart_data_new[test, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="knn-model" class="level1">
<h1>kNN Model</h1>
<p>We will fit a kNN model with 10 fold cross validation with 3 repeats. We will consider k values from 1 to 40 and select the value of k that maximizes accuracy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>trctrl <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"repeatedcv"</span>, <span class="at">number =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">17</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>knn_fit <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDiseaseFactor <span class="sc">~</span> ., <span class="at">data =</span> HeartTrain <span class="sc">|&gt;</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                                          <span class="fu">select</span>(<span class="fu">where</span>(is.numeric), HeartDiseaseFactor)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>                 , <span class="at">method =</span> <span class="st">"knn"</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trControl=</span>trctrl,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>),</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneLength =</span> <span class="dv">40</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>knn_fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>k-Nearest Neighbors 

734 samples
 17 predictor
  2 classes: '0', '1' 

Pre-processing: centered (17), scaled (17) 
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 661, 660, 661, 660, 661, 661, ... 
Resampling results across tuning parameters:

  k   Accuracy   Kappa    
   5  0.8096088  0.6140261
   7  0.8210547  0.6371280
   9  0.8174017  0.6292011
  11  0.8096637  0.6143719
  13  0.8064918  0.6080137
  15  0.8010189  0.5979151
  17  0.8033202  0.6016895
  19  0.8042396  0.6034781
  21  0.8060539  0.6067490
  23  0.8005744  0.5953000
  25  0.8005746  0.5949727
  27  0.7992291  0.5914992
  29  0.7965079  0.5862017
  31  0.7983160  0.5896105
  33  0.7992229  0.5905865
  35  0.7996552  0.5915857
  37  0.8037893  0.5992660
  39  0.8028822  0.5968124
  41  0.8024134  0.5962326
  43  0.8065045  0.6044952
  45  0.8074116  0.6065681
  47  0.8073994  0.6064977
  49  0.8060479  0.6038160
  51  0.8069795  0.6057799
  53  0.8046842  0.6013264
  55  0.8028457  0.5976712
  57  0.8037649  0.5992349
  59  0.8033145  0.5983603
  61  0.8055793  0.6029931
  63  0.8074057  0.6068252
  65  0.8096642  0.6112395
  67  0.8146563  0.6214312
  69  0.8119533  0.6159830
  71  0.8124099  0.6167213
  73  0.8105896  0.6130210
  75  0.8128483  0.6175983
  77  0.8119353  0.6157545
  79  0.8119289  0.6156735
  81  0.8123548  0.6164986
  83  0.8096702  0.6110877

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was k = 7.</code></pre>
</div>
</div>
<p>Based on the results of the kNN cross validation, we can see that the optimal tuning parameter is at k = 7. We will use this model on the test set to predict the values of our response variable. Then we will look at a confusion matrix of</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>knn_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(knn_fit, <span class="at">newdata =</span> HeartTest)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> HeartTest<span class="sc">$</span>HeartDiseaseFactor, <span class="at">reference =</span> knn_predictions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  0  1
         0 74 15
         1 14 81
                                          
               Accuracy : 0.8424          
                 95% CI : (0.7816, 0.8918)
    No Information Rate : 0.5217          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.6843          
                                          
 Mcnemar's Test P-Value : 1               
                                          
            Sensitivity : 0.8409          
            Specificity : 0.8438          
         Pos Pred Value : 0.8315          
         Neg Pred Value : 0.8526          
             Prevalence : 0.4783          
         Detection Rate : 0.4022          
   Detection Prevalence : 0.4837          
      Balanced Accuracy : 0.8423          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
<p>Our model with k = 7 had 84.24% accuracy in predicting the test set of data.</p>
</section>
<section id="logisitic-regression-model" class="level1">
<h1>Logisitic Regression Model</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>Logistic_Model_1 <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDiseaseFactor <span class="sc">~</span> Age <span class="sc">+</span> MaxHR <span class="sc">+</span> Cholesterol, <span class="at">data =</span> HeartTrain, </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method =</span> <span class="st">"glm"</span>,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> <span class="st">"binomial"</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trControl=</span>trctrl,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>))</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Logistic_Model_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
NULL

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  0.32081    0.08380   3.828 0.000129 ***
Age          0.36713    0.09063   4.051 5.11e-05 ***
MaxHR       -0.70172    0.09739  -7.205 5.80e-13 ***
Cholesterol -0.38371    0.09050  -4.240 2.24e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1005.98  on 733  degrees of freedom
Residual deviance:  854.19  on 730  degrees of freedom
AIC: 862.19

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>In this model, all of the predictors are significant. The AIC of the model is 862.19. We will now add RestingBP into the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>Logistic_Model_2 <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDiseaseFactor <span class="sc">~</span> Age <span class="sc">+</span> MaxHR <span class="sc">+</span> Cholesterol <span class="sc">+</span> RestingBP, <span class="at">data =</span> HeartTrain, </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method =</span> <span class="st">"glm"</span>,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> <span class="st">"binomial"</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trControl=</span>trctrl,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>))</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Logistic_Model_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
NULL

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  0.32238    0.08391   3.842 0.000122 ***
Age          0.34573    0.09319   3.710 0.000207 ***
MaxHR       -0.69861    0.09743  -7.171 7.47e-13 ***
Cholesterol -0.39894    0.09221  -4.326 1.52e-05 ***
RestingBP    0.08566    0.08761   0.978 0.328188    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1005.98  on 733  degrees of freedom
Residual deviance:  853.23  on 729  degrees of freedom
AIC: 863.23

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>As we can see, the restingBP predictor is not significant to our model and the AIC of the second model is more than the first model. Therefore, the first model is a better fit than the second. Next, we will take out RestingBP from the model and add Sex to it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>Logistic_Model_3 <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDiseaseFactor <span class="sc">~</span> Age <span class="sc">+</span> MaxHR <span class="sc">+</span> Cholesterol <span class="sc">+</span> Sex, <span class="at">data =</span> HeartTrain, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method =</span> <span class="st">"glm"</span>,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> <span class="st">"binomial"</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trControl=</span>trctrl,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>))</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Logistic_Model_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
NULL

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  0.31113    0.08617   3.611 0.000306 ***
Age          0.38054    0.09346   4.072 4.67e-05 ***
MaxHR       -0.65340    0.09979  -6.548 5.84e-11 ***
Cholesterol -0.29921    0.09275  -3.226 0.001255 ** 
SexM         0.51876    0.08907   5.824 5.73e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1005.98  on 733  degrees of freedom
Residual deviance:  817.52  on 729  degrees of freedom
AIC: 827.52

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>When we add Sex into the logistic regression model, we can see that it is very significant. The AIC of the new model is 827.52, which is about 35 units less than the AIC of the other two models, meaning that it is more accurate. We will use this model for our prediction of the test set.</p>
<p>As we can see from the model, the coefficients of the age and sex variables are positive and the coefficients maximum heart rate and cholesterol are negative. Holding all other variables constant, the variables that have positive coefficients increase the log odds of having heart disease and the opposite is true of those that have negative coefficients.</p>
<p>Next, we will use this model to predict the test set of data and explore how the model did by using a confusion matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>LR_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(Logistic_Model_3, <span class="at">newdata =</span> HeartTest)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> HeartTest<span class="sc">$</span>HeartDiseaseFactor, <span class="at">reference =</span> LR_predictions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  0  1
         0 65 24
         1 21 74
                                          
               Accuracy : 0.7554          
                 95% CI : (0.6868, 0.8157)
    No Information Rate : 0.5326          
    P-Value [Acc &gt; NIR] : 3.87e-10        
                                          
                  Kappa : 0.5098          
                                          
 Mcnemar's Test P-Value : 0.7656          
                                          
            Sensitivity : 0.7558          
            Specificity : 0.7551          
         Pos Pred Value : 0.7303          
         Neg Pred Value : 0.7789          
             Prevalence : 0.4674          
         Detection Rate : 0.3533          
   Detection Prevalence : 0.4837          
      Balanced Accuracy : 0.7555          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
<p>As we can see from the confusion matrix, our final logistic regression model has 75.54% accuracy in terms of predicting the test set.</p>
</section>
<section id="tree-models" class="level1">
<h1>Tree Models</h1>
<section id="classification-tree-model" class="level2">
<h2 class="anchored" data-anchor-id="classification-tree-model">Classification Tree Model</h2>
<p>First we will fit a classification tree model on our data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>classification_Tree <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDiseaseFactor <span class="sc">~</span> Age <span class="sc">+</span> Sex <span class="sc">+</span> MaxHR <span class="sc">+</span> Cholesterol <span class="sc">+</span> ExerciseAngina, <span class="at">data =</span> HeartTrain, </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trControl=</span>trctrl,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>),</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">tuneGrid =</span> <span class="fu">expand.grid</span>(<span class="at">cp =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="fl">0.1</span>, <span class="at">by=</span><span class="fl">0.001</span>)))</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>classification_Tree</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CART 

734 samples
  5 predictor
  2 classes: '0', '1' 

Pre-processing: centered (5), scaled (5) 
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 661, 660, 661, 661, 661, 661, ... 
Resampling results across tuning parameters:

  cp     Accuracy   Kappa    
  0.000  0.7575680  0.5028460
  0.001  0.7616652  0.5111529
  0.002  0.7675644  0.5243938
  0.003  0.7711804  0.5327793
  0.004  0.7753023  0.5429575
  0.005  0.7766783  0.5460549
  0.006  0.7816642  0.5571188
  0.007  0.7839226  0.5622383
  0.008  0.7839226  0.5622383
  0.009  0.7793749  0.5529667
  0.010  0.7789121  0.5527117
  0.011  0.7679899  0.5303633
  0.012  0.7679961  0.5319383
  0.013  0.7702545  0.5399204
  0.014  0.7775049  0.5547890
  0.015  0.7775049  0.5548868
  0.016  0.7775049  0.5548868
  0.017  0.7788747  0.5578573
  0.018  0.7802261  0.5602219
  0.019  0.7802261  0.5602219
  0.020  0.7802261  0.5602219
  0.021  0.7802261  0.5602219
  0.022  0.7802261  0.5602219
  0.023  0.7802261  0.5602219
  0.024  0.7802261  0.5602219
  0.025  0.7802261  0.5602219
  0.026  0.7802261  0.5602219
  0.027  0.7802261  0.5602219
  0.028  0.7802261  0.5602219
  0.029  0.7802261  0.5602219
  0.030  0.7802261  0.5602219
  0.031  0.7802261  0.5602219
  0.032  0.7802261  0.5602219
  0.033  0.7802261  0.5602219
  0.034  0.7802261  0.5602219
  0.035  0.7802261  0.5602219
  0.036  0.7802261  0.5602219
  0.037  0.7802261  0.5602219
  0.038  0.7802261  0.5602219
  0.039  0.7802261  0.5602219
  0.040  0.7802261  0.5602219
  0.041  0.7802261  0.5602219
  0.042  0.7802261  0.5602219
  0.043  0.7802261  0.5602219
  0.044  0.7802261  0.5602219
  0.045  0.7802261  0.5602219
  0.046  0.7802261  0.5602219
  0.047  0.7802261  0.5602219
  0.048  0.7802261  0.5602219
  0.049  0.7802261  0.5602219
  0.050  0.7802261  0.5602219
  0.051  0.7802261  0.5602219
  0.052  0.7802261  0.5602219
  0.053  0.7802261  0.5602219
  0.054  0.7802261  0.5602219
  0.055  0.7802261  0.5602219
  0.056  0.7802261  0.5602219
  0.057  0.7802261  0.5602219
  0.058  0.7802261  0.5602219
  0.059  0.7802261  0.5602219
  0.060  0.7802261  0.5602219
  0.061  0.7802261  0.5602219
  0.062  0.7802261  0.5602219
  0.063  0.7802261  0.5602219
  0.064  0.7802261  0.5602219
  0.065  0.7802261  0.5602219
  0.066  0.7802261  0.5602219
  0.067  0.7802261  0.5602219
  0.068  0.7802261  0.5602219
  0.069  0.7802261  0.5602219
  0.070  0.7802261  0.5602219
  0.071  0.7802261  0.5602219
  0.072  0.7802261  0.5602219
  0.073  0.7802261  0.5602219
  0.074  0.7802261  0.5602219
  0.075  0.7802261  0.5602219
  0.076  0.7802261  0.5602219
  0.077  0.7802261  0.5602219
  0.078  0.7802261  0.5602219
  0.079  0.7802261  0.5602219
  0.080  0.7802261  0.5602219
  0.081  0.7802261  0.5602219
  0.082  0.7802261  0.5602219
  0.083  0.7802261  0.5602219
  0.084  0.7802261  0.5602219
  0.085  0.7802261  0.5602219
  0.086  0.7802261  0.5602219
  0.087  0.7802261  0.5602219
  0.088  0.7802261  0.5602219
  0.089  0.7802261  0.5602219
  0.090  0.7802261  0.5602219
  0.091  0.7802261  0.5602219
  0.092  0.7802261  0.5602219
  0.093  0.7802261  0.5602219
  0.094  0.7802261  0.5602219
  0.095  0.7802261  0.5602219
  0.096  0.7802261  0.5602219
  0.097  0.7802261  0.5602219
  0.098  0.7802261  0.5602219
  0.099  0.7802261  0.5602219
  0.100  0.7802261  0.5602219

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was cp = 0.008.</code></pre>
</div>
</div>
<p>The turning parameter with the highest accuracy was cp = .006. We will use this to make predictions and a confusion matrix on our test set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>CT_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(classification_Tree, <span class="at">newdata =</span> HeartTest)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> HeartTest<span class="sc">$</span>HeartDiseaseFactor, <span class="at">reference =</span> LR_predictions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  0  1
         0 65 24
         1 21 74
                                          
               Accuracy : 0.7554          
                 95% CI : (0.6868, 0.8157)
    No Information Rate : 0.5326          
    P-Value [Acc &gt; NIR] : 3.87e-10        
                                          
                  Kappa : 0.5098          
                                          
 Mcnemar's Test P-Value : 0.7656          
                                          
            Sensitivity : 0.7558          
            Specificity : 0.7551          
         Pos Pred Value : 0.7303          
         Neg Pred Value : 0.7789          
             Prevalence : 0.4674          
         Detection Rate : 0.3533          
   Detection Prevalence : 0.4837          
      Balanced Accuracy : 0.7555          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
<p>The classification tree model had 75.54% accuracy in predicting the test set.</p>
</section>
<section id="random-forest-model" class="level2">
<h2 class="anchored" data-anchor-id="random-forest-model">Random Forest Model</h2>
<p>Next, we will fit a random forest model on our training set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>randomForestModel <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDiseaseFactor <span class="sc">~</span> Age <span class="sc">+</span> Sex <span class="sc">+</span> MaxHR <span class="sc">+</span> Cholesterol <span class="sc">+</span> ExerciseAngina, <span class="at">data =</span> HeartTrain, </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method =</span> <span class="st">"rf"</span>,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trControl=</span>trctrl,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>),</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">tuneGrid =</span> <span class="fu">data.frame</span>(<span class="at">mtry =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>))</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>randomForestModel</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest 

734 samples
  5 predictor
  2 classes: '0', '1' 

Pre-processing: centered (5), scaled (5) 
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 661, 661, 660, 661, 660, 660, ... 
Resampling results across tuning parameters:

  mtry  Accuracy   Kappa    
  1     0.7961496  0.5861832
  2     0.7865605  0.5661416
  3     0.7665926  0.5246193
  4     0.7597865  0.5119450
  5     0.7593114  0.5112639

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was mtry = 1.</code></pre>
</div>
</div>
<p>The turning parameter with the highest accuracy was mtry = 1. We will use this to make predictions and a confusion matrix on our test set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>RF_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(randomForestModel, <span class="at">newdata =</span> HeartTest)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> HeartTest<span class="sc">$</span>HeartDiseaseFactor, <span class="at">reference =</span> RF_predictions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  0  1
         0 75 14
         1 17 78
                                          
               Accuracy : 0.8315          
                 95% CI : (0.7695, 0.8826)
    No Information Rate : 0.5             
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.663           
                                          
 Mcnemar's Test P-Value : 0.7194          
                                          
            Sensitivity : 0.8152          
            Specificity : 0.8478          
         Pos Pred Value : 0.8427          
         Neg Pred Value : 0.8211          
             Prevalence : 0.5000          
         Detection Rate : 0.4076          
   Detection Prevalence : 0.4837          
      Balanced Accuracy : 0.8315          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
<p>This random forest model had 83.15% accuracy on predicting the test set.</p>
</section>
<section id="boosted-tree-model" class="level2">
<h2 class="anchored" data-anchor-id="boosted-tree-model">Boosted Tree Model</h2>
<p>Next, we will fit a boosted tree model on our training set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>BoostedTreeModel <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDiseaseFactor <span class="sc">~</span> Age <span class="sc">+</span> Sex <span class="sc">+</span> MaxHR <span class="sc">+</span> Cholesterol <span class="sc">+</span> ExerciseAngina, <span class="at">data =</span> HeartTrain, </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method =</span> <span class="st">"gbm"</span>,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trControl=</span>trctrl,</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>),</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">tuneGrid =</span> <span class="fu">expand.grid</span>(<span class="at">n.trees =</span> <span class="fu">c</span>(<span class="dv">25</span>,<span class="dv">50</span>,<span class="dv">100</span>,<span class="dv">200</span>),</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">interaction.depth =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>),</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">shrinkage =</span> <span class="fl">0.1</span>,</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">n.minobsinnode =</span> <span class="dv">10</span>),</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>BoostedTreeModel</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Stochastic Gradient Boosting 

734 samples
  5 predictor
  2 classes: '0', '1' 

Pre-processing: centered (5), scaled (5) 
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 660, 661, 661, 661, 661, 661, ... 
Resampling results across tuning parameters:

  interaction.depth  n.trees  Accuracy   Kappa    
  1                   25      0.7864899  0.5680560
  1                   50      0.7824111  0.5591472
  1                  100      0.7805851  0.5551270
  1                  200      0.7774440  0.5486440
  2                   25      0.7801160  0.5544814
  2                   50      0.7792151  0.5516571
  2                  100      0.7787648  0.5496417
  2                  200      0.7746986  0.5408297
  3                   25      0.7837565  0.5600954
  3                   50      0.7828681  0.5576231
  3                  100      0.7764876  0.5446340
  3                  200      0.7674227  0.5261068

Tuning parameter 'shrinkage' was held constant at a value of 0.1

Tuning parameter 'n.minobsinnode' was held constant at a value of 10
Accuracy was used to select the optimal model using the largest value.
The final values used for the model were n.trees = 25, interaction.depth =
 1, shrinkage = 0.1 and n.minobsinnode = 10.</code></pre>
</div>
</div>
<p>The turning parameters with the highest accuracy were n.trees = 25 and interaction.depth = 1. We will use this to make predictions and a confusion matrix on our test set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>Boosted_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(BoostedTreeModel, <span class="at">newdata =</span> HeartTest)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> HeartTest<span class="sc">$</span>HeartDiseaseFactor, <span class="at">reference =</span> Boosted_predictions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  0  1
         0 75 14
         1 15 80
                                          
               Accuracy : 0.8424          
                 95% CI : (0.7816, 0.8918)
    No Information Rate : 0.5109          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.6846          
                                          
 Mcnemar's Test P-Value : 1               
                                          
            Sensitivity : 0.8333          
            Specificity : 0.8511          
         Pos Pred Value : 0.8427          
         Neg Pred Value : 0.8421          
             Prevalence : 0.4891          
         Detection Rate : 0.4076          
   Detection Prevalence : 0.4837          
      Balanced Accuracy : 0.8422          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
<p>This boosted model had 84.24% accuracy on predicting the test set.</p>
</section>
</section>
<section id="wrap-up" class="level1">
<h1>Wrap Up</h1>
<p>Overall, the model that performed best in terms of accuracy of predicting the test set was the boosted tree model at 84.24% accuracy.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>